### ISSUE TITLE
how can I play audio with videocall plugin?

### ISSUE THREAD

**Issue by yue001** [benwtrent/janus-gateway-android#17]
how can I play audio with videocall plugin in the callback method onRemoteStream，config not play video , thanks so much.

**Comment by benwtrent** [comment]
I followed the example given here: https://github.com/pchab/AndroidRTC. 

To only receive audio, you can change the constraints. As for only attaching an audio stream, I am not sure but there is sure to be an example somewhere on how to do an audio only media stream with WebRtc and android.

**Comment by yue001** [comment]
Thanks, but  the example(https://github.com/pchab/AndroidRTC.) does not work for me ,it looks not for janus; 
With janus-gateway-android, I have done some coding to connect "videocall" plugin on janus server, and I run it on two android devices, when I use A to call B, and B answer the "incomingcall", they both received "accepted" message, but after that , neither of them can play audio. Is there any thing I can do for that? thanks.

**Comment by yue001** [comment]
I resolved my problem, That's it, when I receive a offer, I create a answer with a IPluginHandleWebRTCCallbacks using JanusPluginHandle, and return the jsep of the offer in the method getJsep() of the callback and proportionally implement the other methods;

**Comment by zohaib15** [comment]
Hi yue001
I want to make video call b/w two mobile through Janus. Please you can provide me any example .
i have an example but there i am only able make echo test not call b/w two different client.
Thanks in advance
