### ISSUE TITLE
VideoRoomTest only remote video on android

### ISSUE THREAD

**Issue by cnscns** [benwtrent/janus-gateway-android#30]
when initial renders like bellow

**Comment by cnscns** [comment]
remoteRenders[0] = VideoRendererGui.create(0, 0, 25, 25, VideoRendererGui.ScalingType.SCALE_ASPECT_FILL, true);
        remoteRenders[1] = VideoRendererGui.create(0, 0, 25, 25, VideoRendererGui.ScalingType.SCALE_ASPECT_FILL, true);
        remoteRenders[2] = VideoRendererGui.create(0, 0, 25, 25, VideoRendererGui.ScalingType.SCALE_ASPECT_FILL, true);
        remoteRenders[3] = VideoRendererGui.create(0, 0, 25, 25, VideoRendererGui.ScalingType.SCALE_ASPECT_FILL, true);


there is only remote video on android,when changing the x y,there is no video

**Comment by fukemy** [comment]
same problem here, can someone help
