### ISSUE TITLE
Create custom ui for localRender and remoteRender

### ISSUE THREAD

**Issue by antranvn** [benwtrent/janus-gateway-android#31]
Hello, 
Could you help me how to create custom UI for localRender and remoteRender ?

**Comment by benwtrent** [comment]
You just have to modify the android manifest and define the activity and then paint the screen how you want. 

One has to be careful that the UI thread and the background threads are independent. There are plenty of examples around the internet on how to do this correctly.

**Comment by antranvn** [comment]
Thank you @benwtrent
